/source_lifecycle_manager:
  ros__parameters:
    source_mode: "debug_file" # Доступные режимы: debug_file, git_webhook, plc_polling, know_how_fallback

/file_watcher_node:
  ros__parameters:
    watch_dir: "/tmp/code_debug/"
    debounce_seconds: 0.7

/plc_scraper_node:
  ros__parameters:
    poll_rate_hz: 0.1 # 10 секунд

/code_monitor_node:
  ros__parameters:
    source_mode: "debug_file"
    watch_directory: "/root/ros2_ws/src/sens_analytics/test_code"
    debounce_seconds: 0.7
